In [12]:
import numpy as np
from flexIk import velIk as velIk
from flexIk import inv as inv
from flexIk import invTypes as invTypes

In [13]:
# Generate a random 2x3 matrix with values between 0 and 1
matrix = np.random.rand(2, 3)
print(matrix)

[[0.71288884 0.62675643 0.5189982 ]
 [0.85060551 0.91213769 0.18264886]]


NameError: name 'flexIk' is not defined

In [15]:
# get the inverses from each method and compare the outputs
inv1 = inv(matrix, invTypes.PINV)
inv2 = inv(matrix, invTypes.DLS)
inv3 = inv(matrix, invTypes.SRINV)
print(inv1)
print(inv2)
print(inv3)

[[ 0.20878784  0.36808554]
 [-0.68994199  1.12679233]
 [ 2.47319367 -1.86634253]]
[[ 0.20878784  0.36808554]
 [-0.68994189  1.12679224]
 [ 2.47319341 -1.86634231]]
[[ 0.20878784  0.36808554]
 [-0.68994199  1.12679233]
 [ 2.47319367 -1.86634253]]
